export const activities = {
    location: {
      indoor: [
        'Art Projects (painting, sketching, or digital art)',
        'Write a short story or poem',
        'Start a DIY project (crafts, home decor)',
        'Learn to play a musical instrument (e.g., piano, guitar)',
        'Watch a documentary on a topic you know little about',
        'Create a vision board (cutting out pictures and creating a collage)',
        'Indoor gardening or plant care',
        'Try a new workout routine (Zumba, Pilates, Dance)',
        'Build a puzzle',
        'Create a blog or vlog',
        'Baking challenge (try making a complex dessert)',
        'Virtual museum tour (explore online exhibitions)',
        'Organize your digital photos',
        'Learn how to juggle or try other circus skills',
        'Build a fort out of pillows and blankets',
        'Try a new type of tea or coffee brewing',
        'Host a virtual trivia night with friends',
      ],
      outdoor: [
        'Stargazing and learn constellations',
        'Fly a kite',
        'Join a community clean-up day',
        'Take a photography walk',
        'Try geocaching (a GPS-based treasure hunt)',
        'Volunteer at a local animal shelter',
        'Horseback riding',
        'Plant a tree or start a small garden',
        'Go bird watching and keep a log of species you spot',
        'Take a canoe or kayak trip',
        'Take a day trip to a local historical site',
        'Have a scavenger hunt in a new neighborhood',
        'Take a historical walking tour',
        'Visit a farmer\'s market or street fair',
        'Try slacklining (set up a slackline between trees)',
      ],
    },
    type: {
      solo: [
        'Write a letter to your future self',
        'Take an online course in something you\'re passionate about',
        'Go to a local library and read in a quiet corner',
        'Explore a nearby town and be a tourist in your area',
        'Meditate while listening to ambient music',
        'Create a bucket list of things you want to do in life',
        'Have a solo movie marathon based on a theme (e.g., space films)',
        'Learn a new programming language or skill',
        'Learn calligraphy or hand lettering',
        'Try out abstract photography',
        'Create your own perfume or essential oil blend',
        'Try a new hobby (pottery, knitting, sewing)',
        'Plan and execute a self-care day',
        'Start a podcast or YouTube channel on a niche subject',
        'Go on a solo camping trip or spend the night outdoors',
      ],
      group: [
        'Create a talent show with friends and family',
        'Organize a cooking or bake-off competition',
        'Host a themed costume party',
        'Take a group pottery or painting class',
        'Plan a charity walk or run',
        'Participate in a local escape room',
        'Host a book club meeting',
        'Take a team-building cooking class',
        'Go on a group bike ride around the city',
        'Have a DIY project night where everyone brings something to create',
        'Create a communal art piece, like a mural or sculpture',
        'Take a group photography challenge',
        'Host a murder mystery dinner party',
        'Participate in a hackathon or coding competition',
        'Host a talent contest with a panel of judges',
      ],
      fitness: [
        'Try a new high-intensity interval training (HIIT) workout',
        'Challenge yourself with a 30-day fitness challenge',
        'Attend a local or virtual fitness class (kickboxing, CrossFit)',
        'Take a virtual marathon or cycling race',
        'Try aerial silks or trapeze',
        'Try rock climbing at an indoor climbing gym',
        'Swimming laps at a local pool',
        'Hiking a difficult trail',
        'Go on a long-distance walk or charity walk',
        'Participate in a fitness charity event (e.g., color run, Tough Mudder)',
        'Train for a triathlon',
        'Take a dance class (salsa, tango, etc.)',
        'Do a fitness challenge with a friend (who can do the most push-ups)',
        'Try boxing or kickboxing classes',
        'Take a yoga retreat or a day of yoga practice',
        'Do a home circuit training session with bodyweight exercises',
      ],
    },
  };
  